### ISSUE TITLE
Fehlermeldeung bei bus = I2C()

### ISSUE THREAD

**Issue by kalus-pankow** [dafvid/micropython-bmp280#11]
Hallo,
vorab bin Anfänger!, also nehmt mir mir meine Unwissenheit nicht allzu übel.
Erfasse mit einem ESP32 und einem BMP280 die Temperatur. Bin aber nicht  zufrieden mit den Meßergebnissen. Nun bich ich auf dieses Programm gestossen.
habe bisher I2C wie folgt aufgerufen:

 i2c0_sda = Pin(26)
 i2c0_scl = Pin(27)
 i2c0 = I2C(0, sda = i2c0_sda, scl = i2c0_scl, freq = 10000)

und den Sensor:
 bmp280_i2c = BMP280I2C(0x77, i2c0)  

Wenn ich diesen Code aufrufe, erscheint schon bei:
 bus = I2C()
eine Fehlermeldung:
 TypeError: 'scl' argument required
Wie gesagt Anfänger!!!
Sicherlich muß ich noch Werte für das Argument eingeben, blos welche?

Gruß Klaus

**Comment by dafvid** [comment]
Hi Klaus!
This error is related to the call to I2C() and not related to this library.

I2C() is documented here https://docs.micropython.org/en/latest/library/machine.I2C.html

My guess is that this call

i2c0_scl = Pin(27)

returns a None value. Probably because 27 is not a correct value for your board. Try to add
print(i2c0_scl)
to check the returned value.

-David

**Comment by kalus-pankow** [comment]
Hallo,
danke für die Antwort.
Wenn ich 
print( I2C(0))
eingebe, kommt diese Antwort:
**I2C(0, scl=18, sda=19, freq=430107)**
Diese Pins habe ich auch beschaltet.

Wenn ich 
**bus = I2C(0)
bmp = BMP280(bus)**
aufrufe, kommt folgende Fehlermeldung:

**Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "bmp280.py", line 97, in __init__
  File "bmp280.py", line 126, in _read
OSError: [Errno 19] ENODEV**
 Die Zeile sieht folgendermaßen aus:
125	**def _read(self, addr, size=1):**
126          	**return self._bmp_i2c.readfrom_mem(self._i2c_addr, addr, size**)

irgendwas mit I2C aber was? Ich bin zu sehr Anfänger um das zu deuten!

Gruß
Klaus

**Comment by dafvid** [comment]
Hi!
Try to initiate the I2C device without arguments as I2C(), without 0.

Also add a short sleep before trying to read values. The sensor needs a little time to boot. This error means it can't find the sensor. Either it's unpowered or you're using the wrong pin.

-David

**Comment by kalus-pankow** [comment]
Hallo, danke dss Sie sich die Zeit nehmen.
I2C() ohne Argument bringt sofort Fehlermeldung.
Eine Pause einfügen, bringt auch nichts.

Klaus

**Comment by kalus-pankow** [comment]
Hallo,  mir ist es gelungen das Programm zum Laufen zu bringen:
def __init__(self, i2c_bus, addr=0x77, use_case=BMP280_CASE_HANDHELD_DYN):
addr mußte auf 77 geändert werden.

**Comment by dafvid** [comment]
Nice! Happy coding! Closing the issue.
