### ISSUE TITLE
Some chips may be at address 0x77 vs 0x76

### ISSUE THREAD

**Issue by blackshoals** [dafvid/micropython-bmp280#12]
I have BMP280 that is actually one of the hybrids with an AHT20 Temp/Hum and a BMP280 Temp/Pressure sensor combined. [https://universal-solder.ca/aht20-bmp280-sensor-replaces-bme280/](url). There is note "The I2C address for AHT20 is 0x38, for BMP280 it can be 0x76 or 0x77." and my board turned out to be 0x77. Changing the address in line `    def __init__(self, i2c_bus, addr=0x77, use_case=BMP280_CASE_HANDHELD_DYN):` got it working. Thank you for your useful library.

**Comment by dafvid** [comment]
Hi
You can set the address on initiation like so.
`bmp = BMP280(bus, addr=0x77)`
No need to change the default value in the source.

**Comment by dafvid** [comment]
Closed. Not an issue.

**Comment by blackshoals** [comment]
Thank you, it's a slighly confusing little chip with the 2 I2C addresses and 2 temperature readings. Great repo.
