### ISSUE TITLE
chip id only single byte

### ISSUE THREAD

**Issue by kr-g** [dafvid/micropython-bmp280#9]
following bosch specification (revision 1.26, page 24, section 4.3.1) the chip id is only a single byte 

https://github.com/dafvid/micropython-bmp280/blob/f162a9f55a8ebfdcbc60fe02f7f62d95f49a225d/bmp280.py#L297

https://www.bosch-sensortec.com/products/environmental-sensors/pressure-sensors/bmp280/#documents

**Comment by dafvid** [comment]
Thanks @kr-g! It's fixed now.
